fixed_lag_smoother_node:
  ros__parameters:
    # Fixed-lag smoother configuration
    optimization_frequency: 20.0
    transaction_timeout: 0.01
    lag_duration: 0.5

    motion_models:
      unicycle_3d_motion_model:
        type: fuse_models::Unicycle3D     
  
    unicycle_3d_motion_model: # data to match SINAV config
      process_noise_diagonal: [0.05, 0.05, 0.06,      # x, y, z
                               0.03, 0.03, 0.06,      # roll, pitch, yaw
                               0.025, 0.025, 0.04,    # vx, vy, vz
                               0.01, 0.01, 0.02,      # vroll, vpitch, vyaw 
                               0.001, 0.001, 0.0015]  # ax, ay, az

    sensor_models:
      initial_localization_sensor:
        type: fuse_models::Unicycle3DIgnition
        motion_models: [unicycle_3d_motion_model]
        ignition: true
      zed_odometry:
        type: fuse_models::Odometry3D
        motion_models: [unicycle_3d_motion_model]
      wheels_odometry:
        type: fuse_models::Odometry3D
        motion_models: [unicycle_3d_motion_model]
      imu:
        type: fuse_models::Imu3D
        motion_models: [unicycle_3d_motion_model]
 
    initial_localization_sensor:
      publish_on_startup: true
      initial_state: [0.000, 0.000, 0.000, 
                      0.000, 0.000, 0.000,
                      0.000, 0.000, 0.000,
                      0.000, 0.000, 0.000, 
                      0.000, 0.000, 0.000,]
      initial_sigma: [1.0, 1.0, 1.0, 
                      1.0, 1.0, 1.0,
                      1.0, 1.0, 1.0,
                      1.0, 1.0, 1.0,
                      0.000000001, 0.000000001, 0.000000001]
 
    zed_odometry:
      topic: '/zed_camera/odom_transf'
      position_dimensions: ['x', 'y']
      orientation_dimensions: ['yaw']

    wheels_odometry:
      topic: '/locomotion/odom'
      position_dimensions: ['x', 'y', 'z']
      # orientation_dimensions: ['yaw']
      linear_velocity_dimensions: ['x', 'y']
      angular_velocity_dimensions: ['yaw']
      differential: false
      independent: true

    imu:
      topic: '/localisation/imu/data'
      # orientation_target_frame: 'base_link'
      orientation_dimensions: ['roll', 'pitch']
      twist_target_frame: 'base_link'
      angular_velocity_dimensions: ['roll', 'pitch', 'yaw']
      # linear_acceleration_target_frame: 'base_link'
      # linear_acceleration_dimensions: ['x', 'y']
      differential: false
      independent: true
      # tf_timeout: 0.01

    publishers:
      filtered_publisher:
        type: fuse_models::Odometry3DPublisher

    filtered_publisher:
      topic: 'fuse/odometry/filtered'
      base_link_frame_id: 'base_link'
      odom_frame_id: 'odom'
      map_frame_id: 'map'
      world_frame_id: 'odom'
      publish_tf: false
      predict_to_current_time: false
      publish_frequency: 10.0